/*
 * Class PRX_SystemUtility 
 *
 * Class used for System related variables and constants.
 */
public class PRX_VariableConstant {
    public PRX_VariableConstant(){}
    //Block for CR3239 
    public static final string oppClosedWon   = 'Closed Won';
    public static final string oppClosedLost  = 'Closed Lost';
    public static final string oppSystemAdmin = 'System Administrator';
    public static final string oppErrorStr    = 'Cannot change record as Opportunity\'s Stage is ';
}